<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAITLYN" failures="18" tests="85" name="Runner.TestRunner" time="3532.771" errors="0" timestamp="2025-05-02T23:12:11 CDT" skipped="0">
  <testcase classname="Runner.TestRunner" name="runScenario" time="13.939"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.639"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="19.724"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="58.937"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="74.796"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="64.661">
    <failure message="expected [3] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [3] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_output_in_the_console_from_and(ArrayPageStep.java:134)
at ✽.The user should able to see output in the console from "PracticeQns" and 7(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:123)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="92.582">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:228)
at ✽.The user should see a message from "PracticeQns" and 4(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:221)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.318"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="26.037"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.401"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="25.708"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="59.564">
    <failure message="expected [Submission Successful] but found [Error occurred during submission]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [Error occurred during submission]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:228)
at ✽.The user should see a message from "PracticeQns" and 8(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:143)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="84.350"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="65.080">
    <failure message="expected [Submission Successful] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:228)
at ✽.The user should see a message from "PracticeQns" and 12(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:232)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.355"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.917"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.620"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.793"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="16.755"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.844"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="52.958"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="47.668">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:34)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="78.573"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="45.896"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="73.835">
    <failure message="expected [Submission Successful] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:228)
at ✽.The user should see a message from "PracticeQns" and 6(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:99)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="118.052">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 2(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.536"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="6.367"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.724"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.107">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:228)
at ✽.The user should see a message from "PracticeQns" and 3(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:221)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="19.225">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:321)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.712"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="26.733"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="20.870"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.162"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.459"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="50.676"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="20.324"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.541"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.481"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="19.586"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="13.900"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="47.713"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.247"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.827">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="45.958"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.765"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="19.803"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.883"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="59.842"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="67.930">
    <failure message="expected [Hello, World!] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Hello, World!] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_output_in_the_console_from_and(ArrayPageStep.java:134)
at ✽.The user should able to see output in the console from "TryCode" and 4(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:297)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="54.303"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.698"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="60.036"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.661"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.097"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="82.261">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 3(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:286)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="40.935">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:100)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="62.316"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.844"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="47.398"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="15.655"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.720"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.275"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.317"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.034">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:251)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.972">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.ArrayPageStep.the_user_should_be_redirected_to_practice_page(ArrayPageStep.java:149)
at ✽.The user should be redirected to Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:55)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="24.515"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.982"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="48.187"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="21.742"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="18.469"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="27.308">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:130)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.926">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:70)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.480"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="40.908"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="45.778"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.730">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:123)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:286)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="25.266"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.088"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="21.451"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="20.263"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="27.393"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="63.467"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.923"/>
</testsuite> <!-- Runner.TestRunner -->
