<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KAITLYN" failures="54" tests="296" name="Runner.TestRunner" time="11118.994" errors="3" timestamp="2025-05-12T20:07:07 CDT" skipped="0">
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.766"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.667">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:99)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.283"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.604"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.673"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="25.488"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.808"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.097"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.201"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.443">
    <error message="element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: &#039;4.32.0&#039;, revision: &#039;d17c8aa950&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.3&#039;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [ba3a92fb094d21fdc38ed3e4611114b6, sendKeysToElement {id=f.DBC4E5C4E307B80F957B842CB42C2886.d.1FF64D948D49B4B7AE55B37BDDFD97FF.e.41, value=[Ljava.lang.CharSequence;@534cbb13}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:63130}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:63130/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (ba3a92fb094d21fdc38ed3e4611114b6)] -&gt; xpath: //textarea[@autocorrect=&#039;off&#039;]]
Session ID: ba3a92fb094d21fdc38ed3e4611114b6" type="org.openqa.selenium.ElementNotInteractableException">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [ba3a92fb094d21fdc38ed3e4611114b6, sendKeysToElement {id=f.DBC4E5C4E307B80F957B842CB42C2886.d.1FF64D948D49B4B7AE55B37BDDFD97FF.e.41, value=[Ljava.lang.CharSequence;@534cbb13}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:63130}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:63130/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (ba3a92fb094d21fdc38ed3e4611114b6)] -> xpath: //textarea[@autocorrect='off']]
Session ID: ba3a92fb094d21fdc38ed3e4611114b6
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
at PageObject.TreePageObject.enterCodeTryEditor(TreePageObject.java:180)
at StepDefinitions.TreePageStep.the_user_enters_and_clicks_the_run_button_in_time_complexity_try_editor_page(TreePageStep.java:262)
at ✽.The user enters "Tree" and 1 clicks the Run Button in Tree Data Structure tryEditor page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:360)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.182"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.541"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.968"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.974"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.570"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.235"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.791"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.716"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.016">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:285)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.372">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:109)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.663"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.951"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.868"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.442"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.256"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.220"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.790"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.358">
    <failure message="expected [Submission Successful] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:217)
at ✽.The user should see a message from "PracticeQns" and 8(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:142)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.024"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.394"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.364"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.949"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.689"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="58.653"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.426">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.GraphPageStep.the_user_should_be_able_to_receive_an_alert_message_from_excel_sheet_and(GraphPageStep.java:159)
at ✽.The user should be able to receive an alert message from excel sheet 'Graph' and 5(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/GraphPage.feature:51)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.945"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.307"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.470"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="86.907">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:33)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.411"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.315"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.604">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:382)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.329"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.423"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.923">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.StackPageStep.The_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(StackPageStep.java:101)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:100)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.839">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:216)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.221">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:217)
at ✽.The user should see a message from "PracticeQns" and 4(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:220)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.182"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.229"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="25.639"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.790"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.563"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.033"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.504"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.210"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.874"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.664"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.381"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.576"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.933"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.867">
    <failure message="expected [Submission Successful] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:217)
at ✽.The user should see a message from "PracticeQns" and 12(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:231)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.103">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.359"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.796">
    <failure message="expected [Submission Successful] but found [ Some Tests failed. Please review code]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Submission Successful] but found [ Some Tests failed. Please review code]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:217)
at ✽.The user should see a message from "PracticeQns" and 6(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:98)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.913"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.372"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.962"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.842"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.223"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.782">
    <failure message="expected [Practice Questions] but found [ Practice Questions ]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Practice Questions] but found [ Practice Questions ]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.TreePageStep.the_user_should_be_directed_to_data_structure_page(TreePageStep.java:156)
at ✽.The user should be directed to " Practice Questions " in Tree Data Structure(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:528)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.757"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.177"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.640"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="26.994"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.774"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.786"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="68.137">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.StackPageStep.The_user_should_be_redirected_to_Practice_page_links(StackPageStep.java:125)
at ✽.The user should be redirected to Practice page links(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:49)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.796"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.687"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.744">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:421)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="69.572">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:56)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.063"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.065"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.682">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:148)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.945">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:272)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.116"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.026"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="68.624">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.ArrayPageStep.the_user_should_be_redirected_to_practice_page(ArrayPageStep.java:142)
at ✽.The user should be redirected to Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:120)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.196">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:343)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="55.146">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:161)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.034"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.869">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:71)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="50.008"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.078">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:70)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="40.143"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.982"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.672"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.624"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.785"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.354"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.148"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.917">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:252)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.163"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.934">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:460)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.345"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.076"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.929"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.123"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.895"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.600"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.268"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.953"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.310"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.501"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.668"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.655"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.581"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.502"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.976">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:304)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="101.639">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.StackPageStep.The_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(StackPageStep.java:101)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the 2(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.454"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.635"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="47.431"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.372"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.286"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.137"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.797"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.534"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.308"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="64.069">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.ArrayPageStep.the_user_should_be_redirected_to_practice_page(ArrayPageStep.java:142)
at ✽.The user should be redirected to Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:54)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.210"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.963"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="21.610"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.803"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.276"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.403"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.376">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.GraphPageStep.the_user_should_be_able_to_receive_an_alert_message_from_excel_sheet_and(GraphPageStep.java:159)
at ✽.The user should be able to receive an alert message from excel sheet 'Graph' and 5(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/GraphPage.feature:92)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.696">
    <error message="element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: &#039;4.32.0&#039;, revision: &#039;d17c8aa950&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.3&#039;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [394ced46a369c346d02d497c8e5e3a9b, sendKeysToElement {id=f.0B6A8406231816A635422C79CE33F889.d.D960D17E6686F488D8CBDB5F8EC80A39.e.44, value=[Ljava.lang.CharSequence;@4681a5ee}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:62062}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62062/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (394ced46a369c346d02d497c8e5e3a9b)] -&gt; xpath: //textarea[@autocorrect=&#039;off&#039;]]
Session ID: 394ced46a369c346d02d497c8e5e3a9b" type="org.openqa.selenium.ElementNotInteractableException">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [394ced46a369c346d02d497c8e5e3a9b, sendKeysToElement {id=f.0B6A8406231816A635422C79CE33F889.d.D960D17E6686F488D8CBDB5F8EC80A39.e.44, value=[Ljava.lang.CharSequence;@4681a5ee}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:62062}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62062/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (394ced46a369c346d02d497c8e5e3a9b)] -> xpath: //textarea[@autocorrect='off']]
Session ID: 394ced46a369c346d02d497c8e5e3a9b
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
at PageObject.TreePageObject.enterCodeTryEditor(TreePageObject.java:180)
at StepDefinitions.TreePageStep.the_user_enters_and_clicks_the_run_button_in_time_complexity_try_editor_page(TreePageStep.java:262)
at ✽.The user enters "Tree" and 2 clicks the Run Button in Tree Data Structure tryEditor page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:243)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.604"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.957"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.963"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.048"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.636"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.504"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.835"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.096"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.402"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.672"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="51.488"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="52.944"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.844"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.937"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.548"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.540"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.210">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.StackPageStep.The_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(StackPageStep.java:101)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.559"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.822"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.133">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:226)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.052"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.210">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:320)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="21.882"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.350"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.214">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:237)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.663">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:31)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="47.348"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.273"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="23.042"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="52.754">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:126)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.517"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.029"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.790"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="46.115"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.174"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.479">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.StackPageStep.The_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(StackPageStep.java:101)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.681"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="52.550">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:178)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.771"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="62.301"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.681"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.778"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.921"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="23.421"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="40.496"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="67.167">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.ArrayPageStep.the_user_should_be_redirected_to_practice_page(ArrayPageStep.java:142)
at ✽.The user should be redirected to Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/StackPage.feature:84)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.952"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.277"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.751"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="26.300"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.741"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.884"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.275"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.212"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.280"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="99.555">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  2(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.030"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="27.754"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.532"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.287"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.227"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.582"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="95.350">
    <failure message="expected [Hello, World!] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Hello, World!] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_the_output_in_the_console_from_excel_sheet_and_the(LinkeListStep.java:138)
at ✽.The user should able to see the  output in the console from excel sheet "TryCode" and the 4(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:82)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.833"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.995"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.397">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:129)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.455"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.592">
    <failure message="expected [Error occurred during submission] but found [ No tests were collected]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Error occurred during submission] but found [ No tests were collected]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at StepDefinitions.ArrayPageStep.the_user_should_see_a_message(ArrayPageStep.java:217)
at ✽.The user should see a message from "PracticeQns" and 3(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:220)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.774"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.954"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.922"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.594"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.317"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.366"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.019"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="55.039"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.093"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.966"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.189"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.552"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.553"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.120"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.312"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.386"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.375"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.679"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.275"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.886"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.148"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.744"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.190"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.936">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:250)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="40.921"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.353"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.119"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.944"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.459"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.057"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.509"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.215">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:106)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.964"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.062"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.523"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="45.868">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/ArrayPage.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="55.764"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.777"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.646"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.025"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.027"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.526"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.961"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.176"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.577"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.103"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.684"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="62.614">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:91)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.179"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="42.089"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.738"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.322"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="60.773">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.ArrayPageStep.the_user_should_able_to_see_a_error_message_from_and(ArrayPageStep.java:121)
at ✽.The user should able to see a error message from "TryCode" and 1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/QueuePage.feature:69)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.117"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.373"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.264"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="23.397"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.041"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.804"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.556"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.249"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.103"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="39.690"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.927"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.358"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.958"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="44.828">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:187)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.676">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:265)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.532"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.353"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.063"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="35.884"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="41.218"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="43.198"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="22.809"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.663"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.634"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.217"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="33.139"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.520"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="37.993">
    <error message="element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: &#039;4.32.0&#039;, revision: &#039;d17c8aa950&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;21.0.3&#039;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [51646ee0158ed9a3bb5a4f5ba1afb02b, sendKeysToElement {id=f.7DB812C25218E2AE6E8A7BF7E0B7625B.d.48671C16E0F3F51631962EADFA1CAC31.e.43, value=[Ljava.lang.CharSequence;@4b18cf18}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:62084}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62084/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (51646ee0158ed9a3bb5a4f5ba1afb02b)] -&gt; xpath: //textarea[@autocorrect=&#039;off&#039;]]
Session ID: 51646ee0158ed9a3bb5a4f5ba1afb02b" type="org.openqa.selenium.ElementNotInteractableException">
      <![CDATA[org.openqa.selenium.ElementNotInteractableException: element not interactable
  (Session info: MicrosoftEdge=136.0.3240.64)
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.3'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [51646ee0158ed9a3bb5a4f5ba1afb02b, sendKeysToElement {id=f.7DB812C25218E2AE6E8A7BF7E0B7625B.d.48671C16E0F3F51631962EADFA1CAC31.e.43, value=[Ljava.lang.CharSequence;@4b18cf18}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 136.0.3240.64, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:62084}, msedge: {msedgedriverVersion: 136.0.3240.64 (e3a39d3fa3c6..., userDataDir: C:\Users\jimre\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:62084/devtoo..., se:cdpVersion: 136.0.3240.64, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (51646ee0158ed9a3bb5a4f5ba1afb02b)] -> xpath: //textarea[@autocorrect='off']]
Session ID: 51646ee0158ed9a3bb5a4f5ba1afb02b
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:110)
at PageObject.TreePageObject.enterCodeTryEditor(TreePageObject.java:180)
at StepDefinitions.TreePageStep.the_user_enters_and_clicks_the_run_button_in_time_complexity_try_editor_page(TreePageStep.java:262)
at ✽.The user enters "Tree" and 1 clicks the Run Button in Tree Data Structure tryEditor page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:243)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="38.087"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.339">
    <failure message="No Practise Questions found expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Practise Questions found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at StepDefinitions.LinkeListStep.the_user_should_be_redirected_to_the_practice_page(LinkeListStep.java:151)
at ✽.The user should be redirected to the Practice page(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:200)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="28.228"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="34.679">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.DataStructurePageObject.acceptAlert(DataStructurePageObject.java:141)
at StepDefinitions.DataStructureStep.the_user_should_able_to_see_a_error_message_from_and_on_time_complexity_try_editor_popup(DataStructureStep.java:152)
at ✽.The user should able to see a error message from "DataStructures" and 4 on Time Complexity tryEditor popup(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/DataStructure.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="29.393"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="30.195">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepDefinitions.LinkeListStep.the_user_should_able_to_see_a_error_message_from_excel_sheet_and_the(LinkeListStep.java:129)
at ✽.The user should able to see a error message from excel sheet "TryCode" and the  1(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/linkedlist.feature:141)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="32.397"/>
  <testcase classname="Runner.TestRunner" name="runScenario" time="36.355">
    <failure message="No Alert found" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: No Alert found
at org.testng.Assert.fail(Assert.java:111)
at PageObject.TreePageObject.acceptAlert(TreePageObject.java:205)
at StepDefinitions.TreePageStep.the_user_should_able_to_see_a_error_message_from_and_on_tree_try_editor_alert(TreePageStep.java:272)
at ✽.The user should able to see a error message from "Tree" and 4 on Tree Data Structure tryEditor alert(file:///C:/Users/jimre/eclipse-workspace/DSAlgoBDD_ClubNinjas/clubNinjas-BDD/src/test/resources/features/Tree.feature:499)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="Runner.TestRunner" name="runScenario" time="31.779"/>
</testsuite> <!-- Runner.TestRunner -->
